### DISCUSSION TITLE
We should enable auto-index-creation by default in mongoDB

### DISCUSSION THREAD

**Discussion by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#882] [Ideas]
Currently we require users to include the following property in their server.yml properties:

```
spring:
  data:
    mongodb:
      auto-index-creation: true
```

If they do not include this property they get a very big performance hit (x3 in speed). Perhaps we should activate this with a bean to ensure indices are always created automatically?
