### ISSUE TITLE
Doc: how to run: service "ldes-server" depends on undefined service ldes-postgres: invalid compose project

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1300]
Follow the configuration documented at: 
https://informatievlaanderen.github.io/VSDS-LDESServer4J/how-to-run.html#docker-compose
```
services:
  ldes-server:
    container_name: basic_ldes-server
    image: ldes/ldes-server
    environment:
      - SPRING_CONFIG_LOCATION=/config/
    volumes:
      - ./ldes-server.yml:/config/application.yml:ro
    ports:
      - 8080:8080
    networks:
      - ldes
    depends_on:
      - ldes-postgres
  postgres:
    container_name: ldes-postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=test
    networks:
      - ldes
networks:
  ldes:
    name: quick_start_network
```
Get error:
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/e26608ed-ae62-44ee-8568-bd6034f41bd9)

The docker compose should be like:

```
services:
  ldes-server:
    container_name: basic_ldes-server
    image: ldes/ldes-server
    environment:
      - SPRING_CONFIG_LOCATION=/config/
    volumes:
      - ./ldes-server.yml:/config/application.yml:ro
    ports:
      - 8080:8080
    networks:
      - ldes
    depends_on:
      - ldes-postgres
  ldes-postgres:
    container_name: ldes-postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=test
    networks:
      - ldes
networks:
  ldes:
    name: quick_start_network
```

p.s.
https://github.com/Informatievlaanderen/VSDS-LDESServer4J/blob/main/docs/how-to-run.md?plain=1#L38
```
   url: jdbc:postgresql://localhost:5432/test
```
I think it should be

```
   url: jdbc:postgresql://ldes-postgres:5432/test
```

If run in docker with the docker compose demonstrated in the `how-to-run`
Thanks
