### ISSUE TITLE
Include the batch init-schema config in the application settings

### ISSUE THREAD

**Issue by jobulcke** [Informatievlaanderen/VSDS-LDESServer4J#1346]
The followinging config is required in the application.yaml configuration to let the batching processes run successfully:
```yaml
spring:
  batch:
    jdbc:
      initialize-schema: always
```

As this is always the same and required, this could be part of the application settings in the code base itself, so the user does not have to worry about this
