### ISSUE TITLE
Provide alternative option for configuring MongoDB link

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESServer4J#990]
When a MongoDB link needs to be configured with authentication, it is typically done with a spring.data.mongodb.uri, e.g.
```yaml
spring:
  data:
    mongodb:
      uri: mongodb://myDatabaseUser:D1fficultP%40ssw0rd@mongodb0.example.com:27017/?authSource=admin
```
